<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShvmue9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShvmue9/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerShvmue9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerShvmue9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerShvmue9\appProdProjectContainer([
    'container.build_hash' => 'Shvmue9',
    'container.build_id' => '5c37f082',
    'container.build_time' => 1626182149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShvmue9');
