<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgms5tj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgms5tj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNgms5tj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNgms5tj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNgms5tj\appProdProjectContainer([
    'container.build_hash' => 'Ngms5tj',
    'container.build_id' => '5165a587',
    'container.build_time' => 1626172713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgms5tj');
